import os
from pixel_font_builder import (
    FontBuilder,
    WeightName,
    SerifStyle,
    SlantStyle,
    WidthMode,
    Glyph,
    opentype,
)
from datetime import datetime
from PIL import Image
from tqdm import tqdm, trange
from os import listdir

if __name__ == "__main__":
    now = datetime.now()

    builder = FontBuilder()
    builder.font_metric.font_size = 12
    builder.font_metric.horizontal_layout.ascent = 12
    builder.font_metric.horizontal_layout.descent = 0
    builder.font_metric.vertical_layout.ascent = 6
    builder.font_metric.vertical_layout.descent = -6
    builder.font_metric.x_height = 8
    builder.font_metric.cap_height = 10

    builder.meta_info.version = now.strftime("%y%m%d%H%M%S")
    builder.meta_info.family_name = "Rawya Comps"
    builder.meta_info.weight_name = WeightName.REGULAR
    builder.meta_info.serif_style = SerifStyle.SANS_SERIF
    builder.meta_info.slant_style = SlantStyle.NORMAL
    builder.meta_info.width_mode = WidthMode.MONOSPACED
    builder.meta_info.manufacturer = "DWNfonts"
    builder.meta_info.designer = "DWNfonts"
    builder.meta_info.description = "Rawya Comps font, generated by makepfb.py"
    builder.meta_info.copyright_info = "(c) hicc, DWNfonts, 2023-2024"
    builder.meta_info.license_info = "See license on GitHub"
    builder.meta_info.vendor_url = "https://github.com/DWNfonts/Project-Rawya"
    builder.meta_info.designer_url = "https://github.com/DWNfonts"
    builder.meta_info.license_url = (
        "https://github.com/DWNfonts/Project-Rawya/blob/develop/LICENSE.md"
    )
    builder.meta_info.sample_text = "Hello World!"

    部件列表 = listdir("comps/")
    print("正在导入字体…")
    with open("./rycomps.txt", "w", encoding="UTF-8") as g:
        for i in trange(len(部件列表)):
            部件 = 部件列表[i].replace(".png", "")
            g.write(部件 + "\n")
            # print(部件, end="")
            编码 = 0xF0000 + i
            builder.character_mapping.update({编码: 部件})
            部件图 = Image.open("comps/%s.png" % 部件)
            data = []
            for x in range(12):
                line = []
                for y in range(12):
                    a = 部件图.getpixel((y, x))[3]
                    if a > 0:
                        a = 1
                    line.append(a)
                data.append(line)

            builder.glyphs.append(
                Glyph(
                    name=部件,
                    advance_width=0,
                    advance_height=12,
                    horizontal_origin=(0, 0),
                    vertical_origin_y=0,
                    bitmap=data,
                )
            )
            # print("done")

    builder.glyphs.append(
        Glyph(
            name=".notdef",
            advance_width=8,
            advance_height=12,
            horizontal_origin=(0, 0),
            vertical_origin_y=0,
            bitmap=[
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
            ],
        )
    )

    print("正在生成字体…")
    # builder.save_otf("rycomps.otf")
    # builder.save_otf("rycomps.woff2", flavor=opentype.Flavor.WOFF2)
    builder.save_ttf("rycomps.ttf")
    # builder.save_bdf("rycomps.bdf")
    # builder.save_pcf("rycomps.pcf")
