import os
from pixel_font_builder import (
    FontBuilder,
    StyleName,
    SerifMode,
    WidthMode,
    Glyph,
    opentype,
)
from datetime import datetime
from PIL import Image
from tqdm import tqdm, trange
from os import listdir

if __name__ == "__main__":
    now = datetime.now()
    builder = FontBuilder(12)

    builder.meta_info.version = now.strftime("%y%m%d%H%M%S")
    builder.meta_info.family_name = "Rawya (makepfb.py)"
    builder.meta_info.style_name = StyleName.REGULAR
    builder.meta_info.serif_mode = SerifMode.SANS_SERIF
    builder.meta_info.width_mode = WidthMode.MONOSPACED
    builder.meta_info.manufacturer = "DWNfonts"
    builder.meta_info.designer = "DWNfonts"
    builder.meta_info.description = "Rawya, generated by makepfb.py"
    builder.meta_info.copyright_info = "(c) hicc, DWNfonts, 2023-2024"
    builder.meta_info.license_info = "See license on GitHub"
    builder.meta_info.vendor_url = "https://github.com/DWNfonts/Project-Rawya"
    builder.meta_info.designer_url = "https://github.com/DWNfonts"
    builder.meta_info.license_url = (
        "https://github.com/DWNfonts/Project-Rawya/blob/develop/LICENSE.md"
    )
    builder.meta_info.sample_text = "Hello World!"

    builder.horizontal_header.ascent = 12
    builder.horizontal_header.descent = 0

    builder.vertical_header.ascent = 6
    builder.vertical_header.descent = -6

    builder.os2_config.x_height = 8
    builder.os2_config.cap_height = 10

    部件列表 = listdir("out/")
    print("正在导入字体…")
    for i in trange(len(部件列表)):
        部件 = 部件列表[i]
        编码 = ord(部件.replace(".png", ""))
        builder.character_mapping.update({编码: hex(ord(部件.replace(".png", "")))})
        部件图 = Image.open("out/" + 部件)
        data = []
        for x in range(12):
            line = []
            for y in range(12):
                a = 部件图.getpixel((y, x))[3]
                if a > 0:
                    a = 1
                line.append(a)
            data.append(line)

        builder.glyphs.append(
            Glyph(
                name=hex(ord(部件.replace(".png", ""))),
                advance_width=12,
                advance_height=12,
                horizontal_origin=(0, 0),
                vertical_origin_y=0,
                data=data,
            )
        )

    builder.glyphs.append(
        Glyph(
            name=".notdef",
            advance_width=8,
            advance_height=12,
            horizontal_origin=(0, 0),
            vertical_origin_y=0,
            data=[
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
            ],
        )
    )

    print("正在生成字体…")
    builder.save_otf("rawya.otf")
    builder.save_otf("rawya.woff2", flavor=opentype.Flavor.WOFF2)
    builder.save_ttf("rawya.ttf")
    builder.save_bdf("rawya.bdf")
    builder.save_pcf("rawya.pcf")
